name: PR metadata annotation

on:
  push:
    branches:
      - main

jobs:

  prepare-release:
    runs-on: ubuntu-latest
    name: Test github nodejs actions
    
    steps:
      - run: echo ${{github.ref}}
      - name: Checkout this repo
        uses: actions/checkout@v2
        
      - name: Checkout GitHubNodeJsActions Repo
        uses: actions/checkout@v3
        with:
          repository: Brianenno/Artiness.GitHubNodeJsActions
          ref: main
          path: .github/actions/
          token: ${{secrets.GITHUB_TOKEN}}
           
      - name: Prepare release via NodeJs code
        uses: ./.github/actions/
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          push_sha: ${{ github.sha }}