name: PR metadata annotation

on:
  push:
    branches:
      - main

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Test github nodejs actions
      - name: Annotate PR
        uses: link-/Artiness.GitHubNodeJsActions@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}