name: PR metadata annotation

on:
  push:
    branches:
      - main

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout GitHubNodeJsActions Repo
        uses: actions/checkout@v2
        with:
          repository: Brianenno/Artiness.GitHubNodeJsActions
          ref: main
          path: .github/actions/
          token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Change dir
        run: |
            FILE=/.github/actions/action.yml
            if [ -f "$FILE" ]; then
                echo "$FILE exists."
            else 
                echo "$FILE does not exist."
            fi
            
      - name: Move into another dir
        run: cd ..
          
      - name: Print directory content
        run: ls
          
      - name: Move into another dir
        run: cd .github/actions/
          
      - name: Print directory content
        run: ls
           
      - name: Annotate PR
        uses: ./.github/actions/
        id: add-package-source
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}