name: PR metadata annotation

on:
  push:
    branches:
      - main

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout GitHubNodeJsActions Repo
        uses: actions/checkout@v2
        with:
          repository: Brianenno/Artiness.GitHubNodeJsActions
          ref: main
          path: .github/actions/
          token: ${{secrets.GITHUB_TOKEN}}
           
      - name: Run the NodeJs thing
        uses: ./.github/actions/
        working-directory: ./github/actions/
        id: run-the-nodejs-thing
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}